# RAG Configuration for PDF Extractor

# LLM Configuration
llm:
  type: "anthropic"  # openai, anthropic, ollama
  model: "claude-4-opus"  # gpt-4, gpt-4o, gpt-3.5-turbo, claude-4-opus, claude-4-sonnet, claude-4-haiku, claude-3-opus-20240229, claude-3-sonnet-20240229, o3:8b, llama2
  temperature: 0.1
  max_tokens: 2000

# Vector Store Configuration
vector_store:
  type: "chromadb"
  path: "./data/vector_db"
  collection_name: "technical_docs"

# Embedding Configuration
embedding:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  chunk_size: 512
  chunk_overlap: 50

# Retrieval Configuration
retrieval:
  top_k: 5
  similarity_threshold: 0.7

# Chunking Strategy
chunking:
  strategy: "sections"  # sections, tokens, at_commands
  max_tokens: 512
  overlap_tokens: 50

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 